name: CI

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn install
    - name: Build app
      run: yarn android
